作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [25]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
j=0
for i in [english_score,math_score,chinese_score]:
    a=np.nanmean(i)
    b=np.nanmax(i)
    c=np.nanmin(i)
    d=np.nanstd(i)
    if j==0:
        print("英文的平均值:",a,"最大值:",b,"最小值:",c,"標準差:",d)
    elif j==1:
        print("數學的平均值:",a,"最大值:",b,"最小值:",c,"標準差:",d)
    elif j==2:
        print("國文的平均值:",a,"最大值:",b,"最小值:",c,"標準差:",d)
    j+=1

英文的平均值: 67.16666666666667 最大值: 89 最小值: 48 標準差: 13.433995020924426
數學的平均值: 66.6 最大值: 85.0 最小值: 60.0 標準差: 9.707728879609279
國文的平均值: 75.33333333333333 最大值: 90 最小值: 65 標準差: 8.825468196582484


In [29]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4]=55
print(math_score)
a=np.mean(math_score)
b=np.max(math_score)
c=np.min(math_score)
d=np.std(math_score)
print("數學的平均值:",a,"最大值:",b,"最小值:",c,"標準差:",d)

[60. 85. 60. 68. 55. 60.]
數學的平均值: 64.66666666666667 最大值: 85.0 最小值: 55.0 標準差: 9.860132971832694


In [39]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
e=np.corrcoef(english_score,chinese_score)
f=np.corrcoef(math_score,chinese_score)
print(e,"\n",f)
if e.sum()>f.sum():
    print("英文與國文相關度高")
else:
    print("數學與國文相關度高")

[[1.         0.97792828]
 [0.97792828 1.        ]] 
 [[1.         0.74056803]
 [0.74056803 1.        ]]
英文與國文相關度高
